kind: pipeline
name: default

steps:
  - name: install
    image: php7fpm
    commands:
      - cd /var/www/html/cube
      - cp -rf /Moudle /Module_backup
      - cp /Moudle/core/database/Cube.db /Cube_backup.db
      - rm -rf !(/Module_backup Cube_backup.db)
      - git clone https://github.com/wuhan005/Cube
      - cp -rf /Cube/* /
      - rm -rf Module
      - rm /Moudle/core/database/Cube.db
      - cp -rf Module_backup Module
      - rm -rf Module_backup
      - cp /Cube_backup.db /Moudle/core/database/Cube.db
      - rm /Cube_backup.db
